name: Test packages

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      package:
        type: string
        description: "The name of the source package to test"
        required: true
      flavor:
        type: string
        description: "Flavor of the source package to test"
        required: true
      test_type:
        type: string
        description: "The type of test to perform"
        required: true
    # Triggered by pull-request-conditionals.yaml
  workflow_call:
    inputs:
      package:
        type: string
        description: "The name of the source package to test"
        required: true
      flavor:
        type: string
        description: "Flavor of the source package to test"
        required: true
      test_type:
        type: string
        description: "The type of test to perform"
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    name: Test
    env:
      UDS_PKG: ${{ inputs.package }}
    outputs:
      success: ${{ steps.test-single-package.success }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Environment setup
        uses: ./.github/actions/setup

      - name: Login to GHCR
        run: uds run registry-login --set REGISTRY=ghcr.io --set REGISTRY_USERNAME=dummy --set REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }} --set REGISTRY_RETRY_INTERVAL=90

      - name: Test a single source package
        id: test-single-package
        if: ${{ inputs.package != 'all' && inputs.test_type == 'install' }}
        run: |
          uds run test-single-package --set FLAVOR=${{ inputs.flavor }}
          echo "success=success" >> $GITHUB_OUTPUT

      # - name: Test UDS Core Install
      #   if: ${{ inputs.package == 'all' && inputs.test_type == 'install' }}
      #   run: uds run test-uds-core --set FLAVOR=${{ inputs.flavor }}

      # - name: Test UDS Core Upgrade
      #   if: ${{ inputs.package == 'all' && inputs.test_type == 'upgrade' }}
      #   run: uds run test-uds-core-upgrade --set FLAVOR=${{ inputs.flavor }}

      - name: Debug Output
        if: ${{ always() }}
        run: uds run dump-cluster-info

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -${{ inputs.test_type }}-${{ inputs.package }}-${{ inputs.flavor }}

  finish:
    runs-on: "ubuntu-latest"
    name: finish
    needs: test
    steps:
      - run: echo ${{ needs.test.outputs.success }}
